#!/usr/bin/env python3
"""Generates WidgetSourceSnippets.kt from the Compose component sources.

Each component file becomes a `val <camelCaseName>` holding its raw
Kotlin source so the gallery's "copy code" feature stays in sync with
the actual widgets. `$` is escaped as ${'$'} so Kotlin raw strings do
not treat snippet text as string templates.
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COMP = os.path.join(
    ROOT, "app/src/main/java/com/example/widgetgallery/presentation/components")
OUT = os.path.join(
    ROOT, "app/src/main/java/com/example/widgetgallery/data/WidgetSourceSnippets.kt")


def key(filename: str) -> str:
    base = filename[:-3]  # strip .kt
    return base[0].lower() + base[1:]


def main() -> None:
    files = sorted(f for f in os.listdir(COMP) if f.endswith(".kt"))
    out = [
        "// GENERATED by tools/gen_snippets.py — do not edit by hand.",
        "package com.example.widgetgallery.data",
        "",
        "/** Copy-paste-ready Kotlin source for every gallery widget. */",
        "object WidgetSourceSnippets {",
    ]
    for fn in files:
        with open(os.path.join(COMP, fn), encoding="utf-8") as fh:
            code = fh.read().rstrip("\n")
        assert '"""' not in code, fn
        code = code.replace("$", "${'$'}")
        out.append(f'    val {key(fn)} = """')
        out.append(code)
        out.append('"""')
        out.append("")
    out.append("}")
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")
    print("generated", len(files), "snippets ->", os.path.relpath(OUT, ROOT))
    print([key(f) for f in files])


if __name__ == "__main__":
    main()
