// GENERATED by tools/gen_snippets.py — do not edit by hand.
package com.example.widgetgallery.data

/** Copy-paste-ready Kotlin source for every gallery widget. */
object WidgetSourceSnippets {
    val appAvatar = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

internal fun initialsOf(name: String): String {
    val p = name.trim().split(Regex("\\s+"))
    if (p.isEmpty() || p[0].isEmpty()) return "?"
    return if (p.size == 1) p[0].first().uppercase()
    else (p.first().first().toString() + p.last().first()).uppercase()
}

/** Avatar with initials fallback and an optional online status dot. */
@Composable
fun AppAvatar(
    name: String,
    modifier: Modifier = Modifier,
    radius: Dp = 28.dp,
    online: Boolean? = null,
) {
    val scheme = MaterialTheme.colorScheme
    Box(modifier.size(radius * 2)) {
        Box(
            Modifier.size(radius * 2).clip(CircleShape)
                .background(scheme.primaryContainer),
            contentAlignment = Alignment.Center,
        ) {
            Text(initialsOf(name), color = scheme.onPrimaryContainer,
                fontWeight = FontWeight.Bold,
                fontSize = (radius.value * 0.7f).sp)
        }
        if (online != null) {
            Box(
                Modifier
                    .align(Alignment.BottomEnd)
                    .size(radius * 0.55f)
                    .clip(CircleShape)
                    .background(scheme.surface),
                contentAlignment = Alignment.Center,
            ) {
                Box(
                    Modifier.size(radius * 0.4f).clip(CircleShape)
                        .background(
                            if (online) Color(0xFF2E7D32)
                            else Color(0xFF9E9E9E)
                        )
                )
            }
        }
    }
}
"""

    val appBanner = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.filled.Close
import androidx.compose.material.icons.filled.Error
import androidx.compose.material.icons.filled.Info
import androidx.compose.material.icons.filled.WarningAmber
import androidx.compose.material3.Icon
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp

enum class BannerType { Info, Success, Warning, Error }

/** Inline info / success / warning / error banner with dismiss. */
@Composable
fun AppBanner(
    message: String,
    modifier: Modifier = Modifier,
    type: BannerType = BannerType.Info,
    onClose: (() -> Unit)? = null,
) {
    val (bg, fg, icon) = style(type)
    Row(
        modifier
            .clip(RoundedCornerShape(12.dp))
            .background(bg)
            .border(1.dp, fg.copy(alpha = 0.25f), RoundedCornerShape(12.dp))
            .padding(horizontal = 16.dp, vertical = 14.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Icon(icon, null, tint = fg, modifier = Modifier.size(22.dp))
        Spacer(Modifier.width(12.dp))
        Text(message, color = fg, fontWeight = FontWeight.Medium,
            modifier = Modifier.weight(1f))
        if (onClose != null) {
            Spacer(Modifier.width(8.dp))
            Icon(Icons.Filled.Close, null, tint = fg,
                modifier = Modifier.size(18.dp).clickable(onClick = onClose))
        }
    }
}

private data class BannerStyle(val bg: Color, val fg: Color, val icon: ImageVector)

private fun style(t: BannerType): BannerStyle = when (t) {
    BannerType.Success -> BannerStyle(Color(0xFFE6F4EA), Color(0xFF1E7E34),
        Icons.Filled.CheckCircle)
    BannerType.Warning -> BannerStyle(Color(0xFFFFF4E5), Color(0xFFB26A00),
        Icons.Filled.WarningAmber)
    BannerType.Error -> BannerStyle(Color(0xFFFDECEA), Color(0xFFC62828),
        Icons.Filled.Error)
    BannerType.Info -> BannerStyle(Color(0xFFE8F0FE), Color(0xFF1A5DC7),
        Icons.Filled.Info)
}
"""

    val appBottomNavBar = """
package com.example.widgetgallery.presentation.components

import androidx.compose.animation.AnimatedVisibility
import androidx.compose.animation.animateColorAsState
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp

data class BottomNavItem(val icon: ImageVector, val label: String)

/** Pill-style bottom nav where the selected item shows its label. */
@Composable
fun AppBottomNavBar(
    items: List<BottomNavItem>,
    currentIndex: Int,
    onSelect: (Int) -> Unit,
    modifier: Modifier = Modifier,
) {
    val scheme = MaterialTheme.colorScheme
    Row(
        modifier
            .clip(RoundedCornerShape(24.dp))
            .background(scheme.surfaceContainerHighest)
            .padding(horizontal = 12.dp, vertical = 10.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        items.forEachIndexed { i, item ->
            val selected = i == currentIndex
            val bg by animateColorAsState(
                if (selected) scheme.primary else Color.Transparent,
                label = "bg",
            )
            Row(
                Modifier
                    .padding(horizontal = 4.dp)
                    .clip(RoundedCornerShape(18.dp))
                    .background(bg)
                    .clickable { onSelect(i) }
                    .padding(horizontal = 16.dp, vertical = 12.dp),
                verticalAlignment = Alignment.CenterVertically,
            ) {
                Icon(
                    item.icon, null,
                    tint = if (selected) scheme.onPrimary
                    else scheme.onSurfaceVariant,
                    modifier = Modifier.size(22.dp),
                )
                AnimatedVisibility(visible = selected) {
                    Text(
                        "  ${'$'}{item.label}",
                        color = scheme.onPrimary,
                        fontWeight = FontWeight.SemiBold,
                    )
                }
            }
        }
    }
}
"""

    val appButton = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.unit.dp

/** Primary button with optional icon, loading state and full-width. */
@Composable
fun AppButton(
    label: String,
    onClick: () -> Unit,
    modifier: Modifier = Modifier,
    icon: ImageVector? = null,
    loading: Boolean = false,
    fullWidth: Boolean = false,
) {
    Button(
        onClick = onClick,
        enabled = !loading,
        modifier = if (fullWidth) modifier.fillMaxWidth() else modifier,
    ) {
        if (loading) {
            CircularProgressIndicator(
                strokeWidth = 2.4.dp,
                modifier = Modifier.size(20.dp),
                color = MaterialTheme.colorScheme.onPrimary,
            )
        } else {
            if (icon != null) {
                Icon(icon, null, Modifier.size(20.dp))
                Spacer(Modifier.width(8.dp))
            }
            Text(label)
        }
    }
}

/** Secondary outlined action button. */
@Composable
fun AppOutlinedButton(
    label: String,
    onClick: () -> Unit,
    modifier: Modifier = Modifier,
    icon: ImageVector? = null,
    fullWidth: Boolean = false,
) {
    OutlinedButton(
        onClick = onClick,
        modifier = if (fullWidth) modifier.fillMaxWidth() else modifier,
    ) {
        if (icon != null) {
            Icon(icon, null, Modifier.size(20.dp))
            Spacer(Modifier.width(8.dp))
        }
        Text(label)
    }
}
"""

    val appDropdownField = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.DropdownMenuItem
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.ExposedDropdownMenu
import androidx.compose.material3.ExposedDropdownMenuBox
import androidx.compose.material3.ExposedDropdownMenuDefaults
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.MenuAnchorType
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.unit.dp

/** Generic labelled dropdown / select field. */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun <T> AppDropdownField(
    label: String,
    value: T?,
    options: List<T>,
    onSelected: (T) -> Unit,
    modifier: Modifier = Modifier,
    leadingIcon: ImageVector? = null,
    optionLabel: (T) -> String = { it.toString() },
) {
    var expanded by remember { mutableStateOf(false) }
    ExposedDropdownMenuBox(
        expanded = expanded,
        onExpandedChange = { expanded = it },
        modifier = modifier.fillMaxWidth(),
    ) {
        OutlinedTextField(
            value = value?.let(optionLabel) ?: "",
            onValueChange = {},
            readOnly = true,
            label = { Text(label) },
            leadingIcon = leadingIcon?.let { { Icon(it, null) } },
            trailingIcon = {
                ExposedDropdownMenuDefaults.TrailingIcon(expanded = expanded)
            },
            shape = RoundedCornerShape(12.dp),
            modifier = Modifier
                .menuAnchor(MenuAnchorType.PrimaryNotEditable)
                .fillMaxWidth(),
        )
        ExposedDropdownMenu(
            expanded = expanded,
            onDismissRequest = { expanded = false },
        ) {
            options.forEach { option ->
                DropdownMenuItem(
                    text = { Text(optionLabel(option)) },
                    onClick = { onSelected(option); expanded = false },
                )
            }
        }
    }
}
"""

    val appSearchBar = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Close
import androidx.compose.material.icons.filled.Search
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.material3.TextField
import androidx.compose.material3.TextFieldDefaults
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

/** Rounded search field with a clear button. */
@Composable
fun AppSearchBar(
    value: String,
    onValueChange: (String) -> Unit,
    modifier: Modifier = Modifier,
    hint: String = "Search",
) {
    TextField(
        value = value,
        onValueChange = onValueChange,
        placeholder = { Text(hint) },
        leadingIcon = { Icon(Icons.Filled.Search, null) },
        trailingIcon = if (value.isEmpty()) null else {
            {
                IconButton(onClick = { onValueChange("") }) {
                    Icon(Icons.Filled.Close, null)
                }
            }
        },
        singleLine = true,
        shape = RoundedCornerShape(28.dp),
        colors = TextFieldDefaults.colors(
            focusedContainerColor = MaterialTheme.colorScheme.surfaceContainerHighest,
            unfocusedContainerColor = MaterialTheme.colorScheme.surfaceContainerHighest,
            focusedIndicatorColor = Color.Transparent,
            unfocusedIndicatorColor = Color.Transparent,
        ),
        modifier = modifier.fillMaxWidth(),
    )
}
"""

    val appTabBar = """
package com.example.widgetgallery.presentation.components

import androidx.compose.animation.animateColorAsState
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp

/** Controlled segmented top tab bar with an animated pill. */
@Composable
fun AppTabBar(
    tabs: List<String>,
    currentIndex: Int,
    onChange: (Int) -> Unit,
    modifier: Modifier = Modifier,
) {
    val scheme = MaterialTheme.colorScheme
    Row(
        modifier
            .clip(RoundedCornerShape(14.dp))
            .background(scheme.surfaceContainerHighest)
            .padding(4.dp),
    ) {
        tabs.forEachIndexed { i, tab ->
            val selected = i == currentIndex
            val bg by animateColorAsState(
                if (selected) scheme.surface else Color.Transparent,
                label = "tab",
            )
            Box(
                Modifier
                    .weight(1f)
                    .clip(RoundedCornerShape(10.dp))
                    .background(bg)
                    .clickable { onChange(i) }
                    .padding(vertical = 10.dp),
            ) {
                Text(
                    tab,
                    Modifier.fillMaxWidth(),
                    textAlign = TextAlign.Center,
                    fontWeight = FontWeight.SemiBold,
                    color = if (selected) scheme.primary
                    else scheme.onSurfaceVariant,
                )
            }
        }
    }
}
"""

    val appTextField = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Lock
import androidx.compose.material.icons.filled.Visibility
import androidx.compose.material.icons.filled.VisibilityOff
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.text.input.VisualTransformation
import androidx.compose.ui.unit.dp

/** Labelled text field with optional leading icon, helper and error. */
@Composable
fun AppTextField(
    value: String,
    onValueChange: (String) -> Unit,
    label: String,
    modifier: Modifier = Modifier,
    leadingIcon: ImageVector? = null,
    helperText: String? = null,
    errorText: String? = null,
) {
    OutlinedTextField(
        value = value,
        onValueChange = onValueChange,
        label = { Text(label) },
        leadingIcon = leadingIcon?.let { { Icon(it, null) } },
        isError = errorText != null,
        supportingText = (errorText ?: helperText)?.let { { Text(it) } },
        singleLine = true,
        shape = RoundedCornerShape(12.dp),
        modifier = modifier.fillMaxWidth(),
    )
}

/** Password input with a built-in show / hide toggle. */
@Composable
fun PasswordField(
    value: String,
    onValueChange: (String) -> Unit,
    modifier: Modifier = Modifier,
    label: String = "Password",
) {
    var hidden by remember { mutableStateOf(true) }
    OutlinedTextField(
        value = value,
        onValueChange = onValueChange,
        label = { Text(label) },
        leadingIcon = { Icon(Icons.Filled.Lock, null) },
        trailingIcon = {
            IconButton(onClick = { hidden = !hidden }) {
                Icon(
                    if (hidden) Icons.Filled.VisibilityOff
                    else Icons.Filled.Visibility,
                    null,
                )
            }
        },
        visualTransformation = if (hidden) PasswordVisualTransformation()
        else VisualTransformation.None,
        singleLine = true,
        shape = RoundedCornerShape(12.dp),
        modifier = modifier.fillMaxWidth(),
    )
}
"""

    val avatarGroup = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.offset
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/** Overlapping stacked avatars with a +N overflow. */
@Composable
fun AvatarGroup(
    names: List<String>,
    modifier: Modifier = Modifier,
    max: Int = 4,
    radius: Dp = 20.dp,
) {
    val scheme = MaterialTheme.colorScheme
    val shown = names.take(max)
    val overflow = names.size - shown.size
    val step = radius * 1.4f
    Box(modifier) {
        shown.forEachIndexed { i, name ->
            Box(
                Modifier
                    .offset(x = step * i)
                    .size(radius * 2 + 4.dp)
                    .clip(CircleShape)
                    .background(scheme.surface),
                contentAlignment = Alignment.Center,
            ) {
                Box(
                    Modifier.size(radius * 2).clip(CircleShape)
                        .background(scheme.primaryContainer),
                    contentAlignment = Alignment.Center,
                ) {
                    Text(initialsOf(name), color = scheme.onPrimaryContainer,
                        fontWeight = FontWeight.Bold,
                        fontSize = (radius.value * 0.7f).sp)
                }
            }
        }
        if (overflow > 0) {
            Box(
                Modifier
                    .offset(x = step * shown.size)
                    .size(radius * 2 + 4.dp)
                    .clip(CircleShape)
                    .background(scheme.surface),
                contentAlignment = Alignment.Center,
            ) {
                Box(
                    Modifier.size(radius * 2).clip(CircleShape)
                        .background(scheme.secondaryContainer),
                    contentAlignment = Alignment.Center,
                ) {
                    Text("+${'$'}overflow", color = scheme.onSecondaryContainer,
                        fontWeight = FontWeight.Bold,
                        fontSize = (radius.value * 0.7f).sp)
                }
            }
        }
    }
}
"""

    val breadcrumbs = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.FlowRow
import androidx.compose.foundation.layout.ExperimentalLayoutApi
import androidx.compose.foundation.layout.padding
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ChevronRight
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp

/** Tappable path breadcrumb trail. */
@OptIn(ExperimentalLayoutApi::class)
@Composable
fun Breadcrumbs(
    crumbs: List<String>,
    modifier: Modifier = Modifier,
    onClick: (Int) -> Unit = {},
) {
    val scheme = MaterialTheme.colorScheme
    FlowRow(
        modifier,
        verticalArrangement = Arrangement.Center,
    ) {
        crumbs.forEachIndexed { i, crumb ->
            val last = i == crumbs.lastIndex
            Text(
                crumb,
                color = if (last) scheme.onSurface else scheme.primary,
                fontWeight = if (last) FontWeight.Bold else FontWeight.Medium,
                modifier = Modifier
                    .then(if (last) Modifier else Modifier.clickable { onClick(i) })
                    .padding(horizontal = 4.dp, vertical = 2.dp),
            )
            if (!last) {
                Icon(
                    Icons.Filled.ChevronRight, null,
                    tint = scheme.onSurfaceVariant,
                    modifier = Modifier.padding(top = 2.dp),
                )
            }
        }
    }
}
"""

    val checkboxTile = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.material3.Checkbox
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp

/** Tappable checkbox row with title and optional subtitle. */
@Composable
fun CheckboxTile(
    title: String,
    checked: Boolean,
    onCheckedChange: (Boolean) -> Unit,
    modifier: Modifier = Modifier,
    subtitle: String? = null,
) {
    Row(
        modifier
            .fillMaxWidth()
            .clickable { onCheckedChange(!checked) }
            .padding(vertical = 6.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Checkbox(checked = checked, onCheckedChange = onCheckedChange)
        Spacer(Modifier.width(4.dp))
        Column(Modifier.weight(1f)) {
            Text(title, fontWeight = FontWeight.Medium)
            if (subtitle != null) {
                Text(subtitle, style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant)
            }
        }
    }
}
"""

    val circularPercent = """
package com.example.widgetgallery.presentation.components

import androidx.compose.animation.core.animateFloatAsState
import androidx.compose.animation.core.tween
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.size
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlin.math.roundToInt

/** Animated circular progress ring with a centered percentage label. */
@Composable
fun CircularPercent(
    value: Float,
    modifier: Modifier = Modifier,
    size: Dp = 96.dp,
    label: String? = null,
) {
    val animated by animateFloatAsState(
        targetValue = value.coerceIn(0f, 1f),
        animationSpec = tween(700), label = "ring",
    )
    Box(modifier.size(size), contentAlignment = Alignment.Center) {
        CircularProgressIndicator(
            progress = { animated },
            modifier = Modifier.fillMaxSize(),
            strokeWidth = 9.dp,
            trackColor = MaterialTheme.colorScheme.surfaceContainerHighest,
        )
        Column(horizontalAlignment = Alignment.CenterHorizontally) {
            Text("${'$'}{(animated * 100).roundToInt()}%",
                fontSize = (size.value * 0.22f).sp,
                fontWeight = FontWeight.Bold)
            if (label != null) {
                Text(label, fontSize = (size.value * 0.12f).sp,
                    color = MaterialTheme.colorScheme.onSurfaceVariant)
            }
        }
    }
}
"""

    val confirmDialog = """
package com.example.widgetgallery.presentation.components

import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color

/** Reusable confirmation dialog. */
@Composable
fun ConfirmDialog(
    title: String,
    message: String,
    onConfirm: () -> Unit,
    onDismiss: () -> Unit,
    confirmLabel: String = "Confirm",
    cancelLabel: String = "Cancel",
    destructive: Boolean = false,
) {
    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text(title) },
        text = { Text(message) },
        confirmButton = {
            Button(
                onClick = onConfirm,
                colors = if (destructive)
                    ButtonDefaults.buttonColors(
                        containerColor = MaterialTheme.colorScheme.error,
                        contentColor = Color.White,
                    ) else ButtonDefaults.buttonColors(),
            ) { Text(confirmLabel) }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) { Text(cancelLabel) }
        },
    )
}
"""

    val datePickerField = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.CalendarToday
import androidx.compose.material3.DatePicker
import androidx.compose.material3.DatePickerDialog
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.rememberDatePickerState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/** Read-only field that opens a date picker on tap. */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun DatePickerField(
    label: String,
    millis: Long?,
    onPicked: (Long) -> Unit,
    modifier: Modifier = Modifier,
) {
    var open by remember { mutableStateOf(false) }
    val formatter = remember { SimpleDateFormat("dd/MM/yyyy", Locale.getDefault()) }
    val text = millis?.let { formatter.format(Date(it)) } ?: "Select date"

    androidx.compose.foundation.layout.Box(
        modifier.fillMaxWidth().clickable { open = true }
    ) {
        OutlinedTextField(
            value = text,
            onValueChange = {},
            enabled = false,
            readOnly = true,
            label = { Text(label) },
            leadingIcon = { Icon(Icons.Filled.CalendarToday, null) },
            shape = RoundedCornerShape(12.dp),
            modifier = Modifier.fillMaxWidth(),
        )
    }

    if (open) {
        val state = rememberDatePickerState(initialSelectedDateMillis = millis)
        DatePickerDialog(
            onDismissRequest = { open = false },
            confirmButton = {
                TextButton(onClick = {
                    state.selectedDateMillis?.let(onPicked)
                    open = false
                }) { Text("OK") }
            },
            dismissButton = {
                TextButton(onClick = { open = false }) { Text("Cancel") }
            },
        ) { DatePicker(state = state) }
    }
}
"""

    val emptyState = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.material3.Button
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp

/** Placeholder state with icon, title, message and a CTA. */
@Composable
fun EmptyState(
    icon: ImageVector,
    title: String,
    message: String,
    modifier: Modifier = Modifier,
    actionLabel: String? = null,
    onAction: () -> Unit = {},
) {
    val scheme = MaterialTheme.colorScheme
    Column(
        modifier.padding(32.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
    ) {
        Box(
            Modifier.size(96.dp).clip(CircleShape)
                .background(scheme.surfaceContainerHighest),
            contentAlignment = Alignment.Center,
        ) {
            Icon(icon, null, tint = scheme.onSurfaceVariant,
                modifier = Modifier.size(48.dp))
        }
        Spacer(Modifier.height(24.dp))
        Text(title, style = MaterialTheme.typography.titleLarge,
            fontWeight = FontWeight.Bold, textAlign = TextAlign.Center)
        Spacer(Modifier.height(8.dp))
        Text(message, color = scheme.onSurfaceVariant,
            textAlign = TextAlign.Center)
        if (actionLabel != null) {
            Spacer(Modifier.height(24.dp))
            Button(onClick = onAction) { Text(actionLabel) }
        }
    }
}
"""

    val expandablePanel = """
package com.example.widgetgallery.presentation.components

import androidx.compose.animation.AnimatedVisibility
import androidx.compose.animation.core.animateFloatAsState
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.KeyboardArrowDown
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.rotate
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/** Accordion / FAQ panel that animates open and closed. */
@Composable
fun ExpandablePanel(
    title: String,
    modifier: Modifier = Modifier,
    initiallyExpanded: Boolean = false,
    content: @Composable () -> Unit,
) {
    var expanded by remember { mutableStateOf(initiallyExpanded) }
    val rotation by animateFloatAsState(if (expanded) 180f else 0f,
        label = "rot")
    val scheme = MaterialTheme.colorScheme
    Column(
        modifier
            .clip(RoundedCornerShape(14.dp))
            .background(scheme.surfaceContainerLow)
            .border(1.dp, scheme.outlineVariant, RoundedCornerShape(14.dp)),
    ) {
        Row(
            Modifier.fillMaxWidth().clickable { expanded = !expanded }
                .padding(16.dp),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            Text(title, Modifier.weight(1f), fontWeight = FontWeight.SemiBold,
                fontSize = 15.sp)
            Icon(Icons.Filled.KeyboardArrowDown, null,
                modifier = Modifier.rotate(rotation))
        }
        AnimatedVisibility(visible = expanded) {
            Box(Modifier.padding(start = 16.dp, end = 16.dp, bottom = 16.dp)) {
                content()
            }
        }
    }
}
"""

    val filterChipGroup = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.layout.FlowRow
import androidx.compose.foundation.layout.ExperimentalLayoutApi
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.material3.FilterChip
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp

/** A wrap of multi-selectable filter chips. */
@OptIn(ExperimentalLayoutApi::class)
@Composable
fun FilterChipGroup(
    options: List<String>,
    selected: Set<String>,
    onChange: (Set<String>) -> Unit,
    modifier: Modifier = Modifier,
) {
    FlowRow(
        modifier,
        horizontalArrangement = Arrangement.spacedBy(10.dp),
        verticalArrangement = Arrangement.spacedBy(10.dp),
    ) {
        options.forEach { option ->
            val isSel = option in selected
            FilterChip(
                selected = isSel,
                onClick = {
                    onChange(
                        if (isSel) selected - option else selected + option
                    )
                },
                label = { Text(option) },
            )
        }
    }
}
"""

    val gradientButton = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/** Bold gradient call-to-action button. */
@Composable
fun GradientButton(
    label: String,
    onClick: () -> Unit,
    modifier: Modifier = Modifier,
    icon: ImageVector? = null,
    colors: List<Color>? = null,
    fullWidth: Boolean = false,
) {
    val scheme = MaterialTheme.colorScheme
    val gradient = colors ?: listOf(scheme.primary, scheme.tertiary)
    Row(
        modifier
            .then(if (fullWidth) Modifier.fillMaxWidth() else Modifier)
            .clip(RoundedCornerShape(14.dp))
            .background(Brush.horizontalGradient(gradient))
            .clickable(onClick = onClick)
            .padding(horizontal = 24.dp, vertical = 16.dp),
        horizontalArrangement = Arrangement.Center,
        verticalAlignment = Alignment.CenterVertically,
    ) {
        if (icon != null) {
            Icon(icon, null, tint = Color.White, modifier = Modifier.size(20.dp))
            Spacer(Modifier.width(8.dp))
        }
        Text(label, color = Color.White, fontWeight = FontWeight.Bold,
            fontSize = 15.sp)
    }
}
"""

    val imageCard = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Image
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/**
 * Image card with a gradient title overlay. To keep the project
 * dependency-free this renders a themed gradient placeholder; swap in
 * Coil's AsyncImage to load [imageUrl] for real.
 */
@Composable
fun ImageCard(
    imageUrl: String,
    title: String,
    modifier: Modifier = Modifier,
    subtitle: String? = null,
    height: Dp = 180.dp,
) {
    val scheme = MaterialTheme.colorScheme
    Box(
        modifier
            .fillMaxWidth()
            .height(height)
            .clip(RoundedCornerShape(16.dp))
            .clickable {}
            .background(
                Brush.linearGradient(
                    listOf(scheme.primary, scheme.tertiary)
                )
            ),
    ) {
        Icon(
            Icons.Filled.Image, null,
            tint = Color.White.copy(alpha = 0.5f),
            modifier = Modifier.align(Alignment.Center).size(48.dp),
        )
        Box(
            Modifier
                .matchParentSize()
                .background(
                    Brush.verticalGradient(
                        listOf(Color.Transparent, Color.Black.copy(alpha = 0.7f))
                    )
                )
        )
        Column(
            Modifier.align(Alignment.BottomStart)
                .padding(start = 16.dp, end = 16.dp, bottom = 14.dp),
        ) {
            Text(title, color = Color.White, fontSize = 18.sp,
                fontWeight = FontWeight.Bold)
            if (subtitle != null) {
                Text(subtitle, color = Color.White.copy(alpha = 0.8f),
                    fontSize = 13.sp)
            }
        }
    }
}
"""

    val infoCard = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp

/** List-style card with leading icon, title, subtitle and trailing slot. */
@Composable
fun InfoCard(
    icon: ImageVector,
    title: String,
    subtitle: String,
    modifier: Modifier = Modifier,
    onClick: (() -> Unit)? = null,
    trailing: (@Composable () -> Unit)? = null,
) {
    val scheme = MaterialTheme.colorScheme
    Row(
        modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(16.dp))
            .background(scheme.surface)
            .border(1.dp, scheme.outlineVariant, RoundedCornerShape(16.dp))
            .then(if (onClick != null) Modifier.clickable(onClick = onClick) else Modifier)
            .padding(16.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Box(
            Modifier
                .clip(RoundedCornerShape(12.dp))
                .background(scheme.primaryContainer)
                .padding(12.dp),
        ) { Icon(icon, null, tint = scheme.onPrimaryContainer) }
        Spacer(Modifier.width(16.dp))
        Column(Modifier.weight(1f)) {
            Text(title, fontWeight = FontWeight.SemiBold,
                style = MaterialTheme.typography.titleMedium)
            Spacer(Modifier.height(2.dp))
            Text(subtitle, color = scheme.onSurfaceVariant,
                style = MaterialTheme.typography.bodyMedium)
        }
        if (trailing != null) { Spacer(Modifier.width(8.dp)); trailing() }
    }
}
"""

    val keyValueTable = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp

data class KeyValue(val label: String, val value: String)

/** Label / value spec table for detail screens. */
@Composable
fun KeyValueTable(rows: List<KeyValue>, modifier: Modifier = Modifier) {
    val scheme = MaterialTheme.colorScheme
    Column(
        modifier
            .clip(RoundedCornerShape(14.dp))
            .background(scheme.surfaceContainerLow)
            .border(1.dp, scheme.outlineVariant, RoundedCornerShape(14.dp)),
    ) {
        rows.forEachIndexed { i, row ->
            Row(
                Modifier.fillMaxWidth()
                    .padding(horizontal = 16.dp, vertical = 14.dp),
            ) {
                Text(row.label, Modifier.weight(2f),
                    color = scheme.onSurfaceVariant)
                Text(row.value, Modifier.weight(3f),
                    textAlign = TextAlign.End,
                    fontWeight = FontWeight.SemiBold)
            }
            if (i != rows.lastIndex) {
                HorizontalDivider(color = scheme.outlineVariant)
            }
        }
    }
}
"""

    val labeledDivider = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/** Horizontal divider with centered text (e.g. OR). */
@Composable
fun LabeledDivider(label: String, modifier: Modifier = Modifier) {
    val scheme = MaterialTheme.colorScheme
    Row(modifier, verticalAlignment = Alignment.CenterVertically) {
        HorizontalDivider(Modifier.weight(1f), color = scheme.outlineVariant)
        Text(
            label,
            Modifier.padding(horizontal = 14.dp),
            color = scheme.onSurfaceVariant,
            fontWeight = FontWeight.SemiBold,
            fontSize = 12.sp,
        )
        HorizontalDivider(Modifier.weight(1f), color = scheme.outlineVariant)
    }
}
"""

    val labeledProgressBar = """
package com.example.widgetgallery.presentation.components

import androidx.compose.animation.core.animateFloatAsState
import androidx.compose.animation.core.tween
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.LinearProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import kotlin.math.roundToInt

/** Animated labelled progress bar with a percentage readout. */
@Composable
fun LabeledProgressBar(
    label: String,
    value: Float,
    modifier: Modifier = Modifier,
) {
    val animated by animateFloatAsState(
        targetValue = value.coerceIn(0f, 1f),
        animationSpec = tween(600), label = "progress",
    )
    Column(modifier) {
        Row(
            Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
        ) {
            Text(label, fontWeight = FontWeight.SemiBold)
            Text("${'$'}{(animated * 100).roundToInt()}%",
                color = MaterialTheme.colorScheme.onSurfaceVariant)
        }
        Spacer(Modifier.height(8.dp))
        LinearProgressIndicator(
            progress = { animated },
            modifier = Modifier.fillMaxWidth().height(10.dp)
                .clip(RoundedCornerShape(8.dp)),
        )
    }
}

/** Centered spinner with an optional message. */
@Composable
fun LoadingIndicator(
    modifier: Modifier = Modifier,
    message: String? = null,
) {
    Column(
        modifier,
        horizontalAlignment = Alignment.CenterHorizontally,
    ) {
        CircularProgressIndicator()
        if (message != null) {
            Spacer(Modifier.height(16.dp))
            Text(message, color = MaterialTheme.colorScheme.onSurfaceVariant)
        }
    }
}
"""

    val labeledSlider = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.layout.*
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Slider
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import kotlin.math.roundToInt

/** Slider with a label and a live value readout. */
@Composable
fun LabeledSlider(
    label: String,
    value: Float,
    onValueChange: (Float) -> Unit,
    modifier: Modifier = Modifier,
    valueRange: ClosedFloatingPointRange<Float> = 0f..100f,
    unit: String = "",
) {
    Column(modifier) {
        Row(
            Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
        ) {
            Text(label, fontWeight = FontWeight.SemiBold)
            Text("${'$'}{value.roundToInt()}${'$'}unit",
                color = MaterialTheme.colorScheme.primary)
        }
        Slider(
            value = value.coerceIn(valueRange.start, valueRange.endInclusive),
            onValueChange = onValueChange,
            valueRange = valueRange,
        )
    }
}
"""

    val notificationBadge = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.defaultMinSize
import androidx.compose.foundation.layout.offset
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/** Count badge overlaid on any content, with a 99+ cap. */
@Composable
fun NotificationBadge(
    count: Int,
    modifier: Modifier = Modifier,
    color: Color = Color(0xFFE53935),
    content: @Composable () -> Unit,
) {
    Box(modifier) {
        content()
        if (count > 0) {
            Box(
                Modifier
                    .align(Alignment.TopEnd)
                    .offset(x = 6.dp, y = (-6).dp)
                    .defaultMinSize(20.dp, 20.dp)
                    .clip(RoundedCornerShape(20.dp))
                    .background(color)
                    .border(2.dp, MaterialTheme.colorScheme.surface,
                        RoundedCornerShape(20.dp))
                    .padding(horizontal = 5.dp, vertical = 2.dp),
                contentAlignment = Alignment.Center,
            ) {
                Text(
                    if (count > 99) "99+" else "${'$'}count",
                    color = Color.White, fontSize = 11.sp,
                    fontWeight = FontWeight.Bold, textAlign = TextAlign.Center,
                )
            }
        }
    }
}
"""

    val otpInput = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.focus.FocusRequester
import androidx.compose.ui.focus.focusRequester
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/** Fixed-length OTP / PIN entry with auto-advance. */
@Composable
fun OtpInput(
    modifier: Modifier = Modifier,
    length: Int = 4,
    onCompleted: (String) -> Unit = {},
) {
    val cells = remember { mutableStateListOf(*Array(length) { "" }) }
    val focus = remember { List(length) { FocusRequester() } }
    Row(modifier, horizontalArrangement = Arrangement.spacedBy(12.dp)) {
        for (i in 0 until length) {
            OutlinedTextField(
                value = cells[i],
                onValueChange = { raw ->
                    val v = raw.filter { it.isDigit() }.takeLast(1)
                    cells[i] = v
                    if (v.isNotEmpty() && i < length - 1) focus[i + 1].requestFocus()
                    if (v.isEmpty() && i > 0) focus[i - 1].requestFocus()
                    if (cells.all { it.isNotEmpty() }) onCompleted(cells.joinToString(""))
                },
                singleLine = true,
                textStyle = TextStyle(
                    textAlign = TextAlign.Center, fontSize = 20.sp,
                    fontWeight = FontWeight.Bold,
                    color = MaterialTheme.colorScheme.onSurface,
                ),
                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
                shape = RoundedCornerShape(12.dp),
                modifier = Modifier.width(56.dp)
                    .focusRequester(focus[i]),
            )
        }
    }
}
"""

    val priceTag = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextDecoration
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlin.math.roundToInt

/** Price with optional old price and a discount badge. */
@Composable
fun PriceTag(
    price: Double,
    modifier: Modifier = Modifier,
    oldPrice: Double? = null,
    currency: String = "${'$'}",
) {
    val scheme = MaterialTheme.colorScheme
    val hasDiscount = oldPrice != null && oldPrice > price
    val percent = if (hasDiscount)
        (((oldPrice!! - price) / oldPrice) * 100).roundToInt() else 0
    Row(modifier, verticalAlignment = Alignment.Bottom) {
        Text("${'$'}currency${'$'}{"%.2f".format(price)}",
            fontSize = 24.sp, fontWeight = FontWeight.Bold,
            color = scheme.primary)
        if (hasDiscount) {
            Spacer(Modifier.width(8.dp))
            Text("${'$'}currency${'$'}{"%.2f".format(oldPrice)}",
                fontSize = 15.sp, color = scheme.onSurfaceVariant,
                textDecoration = TextDecoration.LineThrough,
                modifier = Modifier.padding(bottom = 3.dp))
            Spacer(Modifier.width(8.dp))
            Box(
                Modifier
                    .padding(bottom = 3.dp)
                    .clip(RoundedCornerShape(6.dp))
                    .background(scheme.errorContainer)
                    .padding(horizontal = 8.dp, vertical = 3.dp),
            ) {
                Text("-${'$'}percent%", color = scheme.onErrorContainer,
                    fontWeight = FontWeight.Bold, fontSize = 12.sp)
            }
        }
    }
}
"""

    val profileCard = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp

private fun initials(name: String): String {
    val p = name.trim().split(Regex("\\s+"))
    if (p.isEmpty() || p[0].isEmpty()) return "?"
    return if (p.size == 1) p[0].first().uppercase()
    else (p.first().first().toString() + p.last().first()).uppercase()
}

/** Profile card with initials avatar, name, role and a primary action. */
@Composable
fun ProfileCard(
    name: String,
    role: String,
    modifier: Modifier = Modifier,
    actionLabel: String? = null,
    onAction: () -> Unit = {},
) {
    val scheme = MaterialTheme.colorScheme
    Column(
        modifier
            .width(260.dp)
            .clip(RoundedCornerShape(20.dp))
            .background(scheme.surface)
            .border(1.dp, scheme.outlineVariant, RoundedCornerShape(20.dp))
            .padding(24.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
    ) {
        Box(
            Modifier.size(80.dp).clip(CircleShape)
                .background(scheme.primaryContainer),
            contentAlignment = Alignment.Center,
        ) {
            Text(initials(name), color = scheme.onPrimaryContainer,
                style = MaterialTheme.typography.headlineSmall,
                fontWeight = FontWeight.Bold)
        }
        Spacer(Modifier.height(16.dp))
        Text(name, style = MaterialTheme.typography.titleLarge,
            fontWeight = FontWeight.Bold)
        Spacer(Modifier.height(4.dp))
        Text(role, color = scheme.onSurfaceVariant,
            style = MaterialTheme.typography.bodyMedium)
        if (actionLabel != null) {
            Spacer(Modifier.height(20.dp))
            Button(onClick = onAction, modifier = Modifier.fillMaxWidth()) {
                Text(actionLabel)
            }
        }
    }
}
"""

    val quantitySelector = """
package com.example.widgetgallery.presentation.components

import androidx.compose.animation.AnimatedContent
import androidx.compose.animation.scaleIn
import androidx.compose.animation.scaleOut
import androidx.compose.animation.togetherWith
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.Remove
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/** Integer stepper clamped between [min] and [max]. */
@Composable
fun QuantitySelector(
    value: Int,
    onValueChange: (Int) -> Unit,
    modifier: Modifier = Modifier,
    min: Int = 0,
    max: Int = 99,
) {
    val scheme = MaterialTheme.colorScheme
    Row(
        modifier
            .clip(RoundedCornerShape(12.dp))
            .background(scheme.surfaceContainerHighest),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        StepBtn(Icons.Filled.Remove, value > min) { onValueChange(value - 1) }
        AnimatedContent(
            targetState = value,
            transitionSpec = { scaleIn() togetherWith scaleOut() },
            label = "qty",
        ) { v ->
            Text("${'$'}v", Modifier.width(44.dp), textAlign = TextAlign.Center,
                fontSize = 16.sp, fontWeight = FontWeight.Bold)
        }
        StepBtn(Icons.Filled.Add, value < max) { onValueChange(value + 1) }
    }
}

@Composable
private fun StepBtn(
    icon: androidx.compose.ui.graphics.vector.ImageVector,
    enabled: Boolean,
    onClick: () -> Unit,
) {
    val scheme = MaterialTheme.colorScheme
    Box(
        Modifier
            .clip(RoundedCornerShape(12.dp))
            .clickable(enabled = enabled, onClick = onClick)
            .padding(12.dp),
    ) {
        Icon(icon, null, Modifier.size(20.dp),
            tint = if (enabled) scheme.onSurface else scheme.outline)
    }
}
"""

    val radioGroup = """
package com.example.widgetgallery.presentation.components

import androidx.compose.animation.core.animateFloatAsState
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.scale
import androidx.compose.ui.unit.dp

/** Single-select option group with a custom indicator. */
@Composable
fun <T> AppRadioGroup(
    options: List<T>,
    value: T?,
    onSelected: (T) -> Unit,
    modifier: Modifier = Modifier,
    optionLabel: (T) -> String = { it.toString() },
) {
    Column(modifier) {
        options.forEach { option ->
            Row(
                Modifier
                    .fillMaxWidth()
                    .clickable { onSelected(option) }
                    .padding(vertical = 10.dp),
                verticalAlignment = Alignment.CenterVertically,
            ) {
                RadioIndicator(selected = option == value)
                Spacer(Modifier.width(14.dp))
                Text(optionLabel(option),
                    style = MaterialTheme.typography.bodyLarge)
            }
        }
    }
}

@Composable
private fun RadioIndicator(selected: Boolean) {
    val scheme = MaterialTheme.colorScheme
    val s by animateFloatAsState(if (selected) 1f else 0f, label = "dot")
    Box(
        Modifier.size(22.dp).clip(CircleShape)
            .border(2.dp, if (selected) scheme.primary else scheme.outline,
                CircleShape),
        contentAlignment = Alignment.Center,
    ) {
        Box(
            Modifier.size(10.dp).scale(s).clip(CircleShape)
                .background(scheme.primary)
        )
    }
}
"""

    val ratingStars = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Row
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Star
import androidx.compose.material.icons.filled.StarBorder
import androidx.compose.material.icons.filled.StarHalf
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import kotlin.math.floor

/** Read-only or interactive star rating. */
@Composable
fun RatingStars(
    rating: Float,
    modifier: Modifier = Modifier,
    max: Int = 5,
    size: Dp = 28.dp,
    color: Color = Color(0xFFFFB300),
    onRatingChange: ((Int) -> Unit)? = null,
) {
    Row(modifier) {
        for (i in 0 until max) {
            val filled = i < floor(rating).toInt()
            val half = !filled && i < rating
            val icon = when {
                filled -> Icons.Filled.Star
                half -> Icons.Filled.StarHalf
                else -> Icons.Filled.StarBorder
            }
            Icon(
                icon, null, tint = color,
                modifier = Modifier
                    .size(size)
                    .then(
                        if (onRatingChange != null)
                            Modifier.clickable { onRatingChange(i + 1) }
                        else Modifier
                    ),
            )
        }
    }
}
"""

    val responsiveGrid = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.BoxWithConstraints
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import kotlin.math.ceil

/** Auto-fitting grid that adapts column count to available width. */
@Composable
fun ResponsiveGrid(
    items: List<@Composable () -> Unit>,
    modifier: Modifier = Modifier,
    maxTileWidth: Dp = 220.dp,
    spacing: Dp = 12.dp,
    aspectRatio: Float = 1.4f,
) {
    BoxWithConstraints(modifier.fillMaxWidth()) {
        val columns = ceil(maxWidth.value / maxTileWidth.value)
            .toInt().coerceIn(1, 6)
        val tileWidth = (maxWidth - spacing * (columns - 1)) / columns
        val rows = items.chunked(columns)
        Column(verticalArrangement = Arrangement.spacedBy(spacing)) {
            rows.forEach { rowItems ->
                Row(horizontalArrangement = Arrangement.spacedBy(spacing)) {
                    rowItems.forEach { item ->
                        Column(
                            Modifier
                                .width(tileWidth)
                                .height(tileWidth / aspectRatio)
                        ) { item() }
                    }
                }
            }
        }
    }
}
"""

    val sectionHeader = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp

/** Section title with subtitle and a trailing action. */
@Composable
fun SectionHeader(
    title: String,
    modifier: Modifier = Modifier,
    subtitle: String? = null,
    actionLabel: String? = null,
    onAction: () -> Unit = {},
) {
    val scheme = MaterialTheme.colorScheme
    Row(modifier.fillMaxWidth()) {
        Box(
            Modifier
                .padding(end = 12.dp, top = 2.dp)
                .width(4.dp)
                .height(if (subtitle != null) 40.dp else 22.dp)
                .clip(RoundedCornerShape(2.dp))
                .background(scheme.primary)
        )
        Column(Modifier.weight(1f)) {
            Text(title, style = MaterialTheme.typography.titleLarge,
                fontWeight = FontWeight.Bold)
            if (subtitle != null) {
                Spacer(Modifier.height(4.dp))
                Text(subtitle, color = scheme.onSurfaceVariant,
                    style = MaterialTheme.typography.bodyMedium)
            }
        }
        if (actionLabel != null) {
            TextButton(onClick = onAction) { Text(actionLabel) }
        }
    }
}
"""

    val selectableListTile = """
package com.example.widgetgallery.presentation.components

import androidx.compose.animation.animateColorAsState
import androidx.compose.animation.core.animateFloatAsState
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material3.Icon
import androidx.compose.material3.ListItem
import androidx.compose.material3.ListItemDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.scale
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp

/** List tile that highlights and checks when selected. */
@Composable
fun SelectableListTile(
    title: String,
    selected: Boolean,
    onClick: () -> Unit,
    modifier: Modifier = Modifier,
    subtitle: String? = null,
    leading: (@Composable () -> Unit)? = null,
) {
    val scheme = MaterialTheme.colorScheme
    val bg by animateColorAsState(
        if (selected) scheme.primaryContainer.copy(alpha = 0.5f)
        else scheme.surfaceContainerLow,
        label = "bg",
    )
    val s by animateFloatAsState(if (selected) 1f else 0f, label = "check")
    ListItem(
        headlineContent = { Text(title, fontWeight = FontWeight.SemiBold) },
        supportingContent = subtitle?.let { { Text(it) } },
        leadingContent = leading,
        trailingContent = {
            Icon(Icons.Filled.CheckCircle, null,
                tint = scheme.primary, modifier = Modifier.scale(s))
        },
        colors = ListItemDefaults.colors(containerColor = bg),
        modifier = modifier
            .clip(RoundedCornerShape(14.dp))
            .border(
                if (selected) 1.5.dp else 1.dp,
                if (selected) scheme.primary else scheme.outlineVariant,
                RoundedCornerShape(14.dp),
            )
            .clickable(onClick = onClick),
    )
}
"""

    val skeletonLoader = """
package com.example.widgetgallery.presentation.components

import androidx.compose.animation.core.RepeatMode
import androidx.compose.animation.core.animateFloat
import androidx.compose.animation.core.infiniteRepeatable
import androidx.compose.animation.core.rememberInfiniteTransition
import androidx.compose.animation.core.tween
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

/** Animated shimmer placeholder for loading content. */
@Composable
fun SkeletonLoader(
    modifier: Modifier = Modifier,
    height: Dp = 16.dp,
    cornerRadius: Dp = 8.dp,
) {
    val base = MaterialTheme.colorScheme.surfaceContainerHighest
    val highlight = MaterialTheme.colorScheme.surfaceContainerLow
    val transition = rememberInfiniteTransition(label = "shimmer")
    val x by transition.animateFloat(
        initialValue = -300f,
        targetValue = 1000f,
        animationSpec = infiniteRepeatable(
            animation = tween(1200), repeatMode = RepeatMode.Restart,
        ),
        label = "x",
    )
    Box(
        modifier
            .fillMaxWidth()
            .height(height)
            .clip(RoundedCornerShape(cornerRadius))
            .background(
                Brush.linearGradient(
                    colors = listOf(base, highlight, base),
                    start = Offset(x, 0f),
                    end = Offset(x + 300f, 0f),
                )
            ),
    )
}
"""

    val statCard = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.TrendingDown
import androidx.compose.material.icons.filled.TrendingUp
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp

/** Compact metric card with icon, value, label and trend delta. */
@Composable
fun StatCard(
    icon: ImageVector,
    value: String,
    label: String,
    modifier: Modifier = Modifier,
    trend: String? = null,
) {
    val scheme = MaterialTheme.colorScheme
    val negative = trend?.trim()?.startsWith("-") == true
    Column(
        modifier
            .width(200.dp)
            .clip(RoundedCornerShape(16.dp))
            .background(scheme.surface)
            .border(1.dp, scheme.outlineVariant, RoundedCornerShape(16.dp))
            .padding(20.dp),
    ) {
        Box(
            Modifier
                .clip(RoundedCornerShape(12.dp))
                .background(scheme.primary.copy(alpha = 0.12f))
                .padding(10.dp),
        ) { Icon(icon, null, tint = scheme.primary) }
        Spacer(Modifier.height(16.dp))
        Text(value, style = MaterialTheme.typography.headlineSmall,
            fontWeight = FontWeight.Bold)
        Spacer(Modifier.height(4.dp))
        Text(label, color = scheme.onSurfaceVariant,
            style = MaterialTheme.typography.bodyMedium)
        if (trend != null) {
            Spacer(Modifier.height(12.dp))
            val c = if (negative) Color(0xFFD32F2F) else Color(0xFF2E7D32)
            Row(verticalAlignment = Alignment.CenterVertically) {
                Icon(
                    if (negative) Icons.Filled.TrendingDown
                    else Icons.Filled.TrendingUp,
                    null, tint = c, modifier = Modifier.size(16.dp),
                )
                Spacer(Modifier.width(4.dp))
                Text(trend, color = c, fontWeight = FontWeight.SemiBold)
            }
        }
    }
}
"""

    val statusBadge = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Close
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlin.math.abs

private val palette = listOf(
    Color(0xFF1A5DC7), Color(0xFF1E7E34), Color(0xFFB26A00),
    Color(0xFFC62828), Color(0xFF6A1B9A),
)

/** Small colored status pill with optional icon. */
@Composable
fun StatusBadge(
    label: String,
    modifier: Modifier = Modifier,
    color: Color? = null,
    icon: ImageVector? = null,
) {
    val c = color ?: palette[abs(label.hashCode()) % palette.size]
    Row(
        modifier
            .clip(RoundedCornerShape(999.dp))
            .background(c.copy(alpha = 0.12f))
            .padding(horizontal = 12.dp, vertical = 6.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        if (icon != null) {
            Icon(icon, null, tint = c, modifier = Modifier.size(14.dp))
            Spacer(Modifier.width(6.dp))
        }
        Text(label, color = c, fontWeight = FontWeight.SemiBold, fontSize = 12.sp)
    }
}

/** Selectable / removable tag chip. */
@Composable
fun TagChip(
    label: String,
    modifier: Modifier = Modifier,
    selected: Boolean = false,
    onClick: () -> Unit = {},
    onRemove: (() -> Unit)? = null,
) {
    val scheme = MaterialTheme.colorScheme
    Row(
        modifier
            .clip(RoundedCornerShape(999.dp))
            .background(
                if (selected) scheme.primary
                else scheme.surfaceContainerHighest
            )
            .clickable(onClick = onClick)
            .padding(horizontal = 14.dp, vertical = 8.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Text(
            label,
            color = if (selected) scheme.onPrimary else scheme.onSurface,
            fontWeight = FontWeight.Medium,
        )
        if (onRemove != null) {
            Spacer(Modifier.width(6.dp))
            Icon(
                Icons.Filled.Close, null,
                tint = if (selected) scheme.onPrimary else scheme.onSurfaceVariant,
                modifier = Modifier.size(16.dp).clickable(onClick = onRemove),
            )
        }
    }
}
"""

    val stepProgress = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Check
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/** Horizontal multi-step indicator for wizards / checkout. */
@Composable
fun StepProgress(
    steps: List<String>,
    currentStep: Int,
    modifier: Modifier = Modifier,
) {
    val scheme = MaterialTheme.colorScheme
    Row(modifier, verticalAlignment = Alignment.Top) {
        steps.forEachIndexed { i, step ->
            Column(
                horizontalAlignment = Alignment.CenterHorizontally,
            ) {
                Box(
                    Modifier.size(30.dp).clip(CircleShape)
                        .background(
                            if (i <= currentStep) scheme.primary
                            else scheme.surfaceContainerHighest
                        ),
                    contentAlignment = Alignment.Center,
                ) {
                    if (i < currentStep) {
                        Icon(Icons.Filled.Check, null,
                            tint = scheme.onPrimary,
                            modifier = Modifier.size(16.dp))
                    } else {
                        Text("${'$'}{i + 1}",
                            color = if (i == currentStep) scheme.onPrimary
                            else scheme.onSurfaceVariant,
                            fontWeight = FontWeight.Bold)
                    }
                }
                Spacer(Modifier.height(6.dp))
                Text(step, fontSize = 11.sp,
                    color = if (i <= currentStep) scheme.primary
                    else scheme.onSurfaceVariant,
                    fontWeight = if (i == currentStep) FontWeight.Bold
                    else FontWeight.Normal)
            }
            if (i != steps.lastIndex) {
                Box(
                    Modifier
                        .weight(1f)
                        .padding(top = 14.dp)
                        .height(2.dp)
                        .background(
                            if (i < currentStep) scheme.primary
                            else scheme.outlineVariant
                        )
                )
            }
        }
    }
}
"""

    val swipeableListItem = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.DeleteOutline
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.ListItem
import androidx.compose.material3.ListItemDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.SwipeToDismissBox
import androidx.compose.material3.SwipeToDismissBoxValue
import androidx.compose.material3.Text
import androidx.compose.material3.rememberSwipeToDismissBoxState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp

/** List row with swipe-to-delete. */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun SwipeableListItem(
    title: String,
    onDismissed: () -> Unit,
    modifier: Modifier = Modifier,
    subtitle: String? = null,
    leading: (@Composable () -> Unit)? = null,
) {
    val scheme = MaterialTheme.colorScheme
    val state = rememberSwipeToDismissBoxState()

    LaunchedEffect(state.currentValue) {
        if (state.currentValue == SwipeToDismissBoxValue.EndToStart) {
            onDismissed()
        }
    }

    SwipeToDismissBox(
        state = state,
        modifier = modifier.clip(RoundedCornerShape(14.dp)),
        enableDismissFromStartToEnd = false,
        backgroundContent = {
            Box(
                Modifier.fillMaxSize()
                    .clip(RoundedCornerShape(14.dp))
                    .background(scheme.errorContainer)
                    .padding(end = 24.dp),
                contentAlignment = Alignment.CenterEnd,
            ) {
                Icon(Icons.Filled.DeleteOutline, null,
                    tint = scheme.onErrorContainer)
            }
        },
    ) {
        ListItem(
            headlineContent = {
                Text(title, fontWeight = FontWeight.SemiBold)
            },
            supportingContent = subtitle?.let { { Text(it) } },
            leadingContent = leading,
            colors = ListItemDefaults.colors(
                containerColor = scheme.surfaceContainerLow,
            ),
            modifier = Modifier
                .clip(RoundedCornerShape(14.dp))
                .border(1.dp, scheme.outlineVariant,
                    RoundedCornerShape(14.dp)),
        )
    }
}
"""

    val switchTile = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp

/** Settings-style row with icon, text and a switch. */
@Composable
fun SwitchTile(
    title: String,
    checked: Boolean,
    onCheckedChange: (Boolean) -> Unit,
    modifier: Modifier = Modifier,
    subtitle: String? = null,
    icon: ImageVector? = null,
) {
    Row(
        modifier
            .fillMaxWidth()
            .clickable { onCheckedChange(!checked) }
            .padding(horizontal = 12.dp, vertical = 10.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        if (icon != null) {
            Icon(icon, null, tint = MaterialTheme.colorScheme.primary)
            Spacer(Modifier.width(16.dp))
        }
        Column(Modifier.weight(1f)) {
            Text(title, fontWeight = FontWeight.Medium)
            if (subtitle != null) {
                Text(subtitle, style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant)
            }
        }
        Switch(checked = checked, onCheckedChange = onCheckedChange)
    }
}
"""

    val timeline = """
package com.example.widgetgallery.presentation.components

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Check
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

data class TimelineEntry(val title: String, val subtitle: String,
    val done: Boolean = false)

/** Vertical timeline / activity feed with connected nodes. */
@Composable
fun Timeline(entries: List<TimelineEntry>, modifier: Modifier = Modifier) {
    val scheme = MaterialTheme.colorScheme
    Column(modifier) {
        entries.forEachIndexed { i, e ->
            Row {
                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                    Box(
                        Modifier.size(18.dp).clip(CircleShape)
                            .background(
                                if (e.done) scheme.primary
                                else scheme.surfaceContainerHighest
                            )
                            .border(2.dp, scheme.primary, CircleShape),
                        contentAlignment = Alignment.Center,
                    ) {
                        if (e.done) Icon(Icons.Filled.Check, null,
                            tint = Color.White, modifier = Modifier.size(11.dp))
                    }
                    if (i != entries.lastIndex) {
                        Box(Modifier.width(2.dp).height(46.dp)
                            .background(scheme.outlineVariant))
                    }
                }
                Spacer(Modifier.width(14.dp))
                Column(Modifier.padding(bottom = 22.dp)) {
                    Text(e.title, fontWeight = FontWeight.SemiBold,
                        fontSize = 15.sp)
                    Spacer(Modifier.height(2.dp))
                    Text(e.subtitle, color = scheme.onSurfaceVariant,
                        fontSize = 13.sp)
                }
            }
        }
    }
}
"""

}
